blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_page, name='home'),
    path('about/', views.about_page, name='about'),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/posts/urls.py
from django.urls import path
from .import views

app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name='list'),
    path('<int:pk>/', views.post_detail, name='detail'),
    path('add-post/', views.post_add, name='add-post')
]

blog/users/urls.py
from django.urls import path
from .import views

app_name = 'users'

urlpatterns = [
    path('register/', views.user_register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout')
]

blog/posts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
    image = models.ImageField(upload_to='posts/images', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title

blog/users/models.py
from django.db import models

# Create your models here.

blog/posts/forms.py
from django import forms
from .models import Post

class CreatePost(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'image']

blog/blog/views.py
from django.shortcuts import render
from posts.models import Post

def home_page(request):
    posts = Post.objects.all().order_by('-id')
    return render(request, 'post_list.html', {'posts':posts})

def about_page(request):
    return render(request, 'about.html')

blog/posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from django.shortcuts import get_object_or_404, render
from .forms import CreatePost
from django.contrib.auth.decorators import login_required

# Create your views here.

def post_list(request):
    posts = Post.objects.all().order_by('-id')
    return render(request, 'post_list.html', {'posts':posts})


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'post_detail.html', {'post':post})

@login_required(login_url='/users/login')
def post_add(request):
    if request.method == 'POST':
        form = CreatePost(request.POST, request.FILES)
        if form.is_valid():
            newpost = form.save(commit=False)
            newpost.author = request.user
            newpost.save()
            return redirect('posts:list')
        
    else:
        form = CreatePost()
    return render(request, 'add_post.html', {'form':form})

blog/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages


# Create your views here.

def user_register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('posts:list')
        else:
            for error in form.errors.values():
                messages.error(request, error)
    else:
        form = UserCreationForm()
    return render(request, 'register.html', {'form':form})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('posts:list')
        else:
            messages.error(request, "Invalid username or password")
            
    return render(request, 'login.html')
        

def user_logout(request):
    if request.method == 'POST':
        logout(request)
        return redirect('posts:list')

blog/posts/templates/add_post.html
{% extends 'base.html' %}

{% block content %}
    <div class="form-container">
        <h2>Create new Post</h2>
        <form enctype="multipart/form-data" method="post">
            {% csrf_token %}

            <div class="form-group">
                <label for="title">Title</label>
                {{form.title}}
            </div>
            <div class="form-group">
                <label for="content">Content</label>
                {{form.content}}
            </div>
            <div class="form-group">
                <label for="image">Image</label>
                {{form.image}}
            </div>
            <button type="submit">Add Post</button>
        </form>
    </div>
{% endblock %}

blog/posts/templates/post_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="detail-title">{{post.title}}</h1>
    <div class="detail-detail">
        {% if post.image %}
            <img src="{{post.image.url}}" alt="Post Image">
        {% endif %}

        <p class="detail-author">By {{post.author}} on {{post.created_at}}</p>
        <div class="detail-content">
            <p>{{post.content}}</p>
        </div>
    </div>
{% endblock %}

blog/posts/templates/post_list.html
{% extends 'base.html' %}

{% block content %}

    <h1 class="page-title">Blog  Posts</h1>
    <div class="post-grid">
        {% for post in posts %}
            <div class="post-card">
                {% if post.image %}
                    <img src="{{post.image.url}}" class="post-image">
                {% endif %}
                <div class="post-content">
                    <h2 class="post-title">{{post.title}}</h2>
                    <p class="post-author">By {{post.author}} on {{post.created_at}}</p>
                    <p class="post-description">{{post.content | truncatechars:25}}</p>
                    <a href="{% url 'posts:detail' post.id %}" class="read-more">Read More ...</a>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

blog/templates/about.html
{% extends 'base.html' %}

{% block content %}
    This is my About Page by Phegon Dev
{% endblock %}

blog/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="{% static 'js/main.js' %}"></script>
</head>
<body>
    <nav class="navbar">
        <div class="logo">
            <img src="" alt="Logo">
        </div>
        <ul>
            <li>
                <a class="nav-link" href="{% url 'home' %}">Home</a>
            </li>
            <li>
                <a class="nav-link" href="{% url 'posts:list' %}">Post</a>
            </li>

            {% if user.is_authenticated %}
            <li>
                <form  class="logout" action="{% url 'users:logout' %}" method="post">
                    {% csrf_token %}
                    <input class="nav-link-input" type="submit" value="Logout" style="background: none; border: none;">
                </form>
            </li>

            {% if user.is_superuser or user.is_staff %}
            <li>
                <a class="nav-link" href="/admin">Admin</a>
            </li>
            {% endif %}

            <li>
                <a class="nav-link" href="{% url 'posts:add-post' %}">Add Post</a>
            </li>
            {% else %}
            <li>
                <a class="nav-link" href="{% url 'users:login' %}">Login</a>
            </li>
            <li>
                <a class="nav-link" href="{% url 'users:register' %}">Register</a>
            </li>
            {% endif %}
            <li>
                <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
        </ul>
    </nav>

    {% block content %}

    {% endblock %}

    <footer class="footer">
        <p>&copy; 2024. All Rights Reserved. Phegon Dev</p>
    </footer>
</body>
</html>

blog/templates/home.html
{% extends 'base.html' %}

{% block content %}
  <h1>Welcome to our home page</h1>
  <a href="{% url 'about' %}">ABOUT PAGE</a>
{% endblock %}

blog/users/templates/login.html
{% extends 'base.html' %}
{% block content %}
  <div class="form-container">
    <h1>Login</h1>

    {% if messages %}
      {% for message in messages %}
        <p>{{ message }}</p>
      {% endfor %}
    {% endif %}

    <form action="{% url 'users:login' %}" method="post">
      {% csrf_token %}
      <div class="form-group">
        <label for="">Username</label>
        <input type="text" name="username" required />
      </div>
      <div class="form-group">
        <label for="">Password</label>
        <input type="password" name="password" required />
      </div>
      <button type="submit">Login</button>
    </form>
    <p>
      Don't have an account?<a href="{% url 'users:register' %}">Register here</a>
    </p>
  </div>
{% endblock %}

blog/users/templates/register.html
{% extends 'base.html' %}
{% block content %}
    <div class="form-container">

        {% if messages %}
            {% for message in messages %}
                <p>{{message}}</p>
            {% endfor %}
        {% endif %}

        <h1>Register</h1>
        <form action="{% url 'users:register' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="">Username</label>
                {{form.username}}
            </div>
            <div class="form-group">
                <label for="">Password</label>
                {{form.password1}}
            </div>
            <div class="form-group">
                <label for="">Confirm Password</label>
                {{form.password2}}
            </div>
            <button type="submit">Register</button>
        </form>
        <p>Already have an account?<a href="{% url 'users:login' %}">Login here</a></p>
    </div>
{% endblock%}